nobe4/howtoxiny

hugo.toml
I thought I liked TOML more than YAML, I'm starting to doubt it.
=> fix(config): move config out of map

.github/workflows/deploy.yaml, .gitignore, assets/js/main.js, assets/js/search.js, assets/jsconfig.json, assets/sass/main.scss, hugo.toml, layouts/_default/baseof.html, layouts/_default/home.html, layouts/_default/term.html, layouts/partials/assets/css.html, layouts/partials/assets/js.html, layouts/partials/debug.html, layouts/partials/head.html, layouts/partials/header.html, layouts/partials/i18n/picker.html, layouts/partials/taxonomy/tree.html, package-lock.json, package.json, script/pagefind, script/serve
This commit is pretty big, it adds the necessary resources and config to integrate pagefind.
=> feat(search): add search bar

i18n/de.toml
- Fix the "how to x IN y" string
=> fix: DE translation one more string

README.md, content/en/docs/contributing.md, layouts/_default/home.html, layouts/partials/i18n/link.html, layouts/partials/i18n/picker.html, layouts/partials/title.html
Also improve various i18n layouts.
=> feat(contributing): add new contributing page

.github/PULL_REQUEST_TEMPLATE.md, LICENSE, content/en/docs/contributing.md, layouts/partials/footer.html, layouts/partials/license.html
- sets the project license
- update the contributing page with legal-ish guidelines
- add the license in the footer and create a template to help newcomers understand the requirements for contributing.
=> feat(license): set the project's license

.tailwind.config.js, assets/js/search.js, layouts/_default/home.html, layouts/partials/search.html
=> feat(css): update search styling

layouts/partials/title.html
I messed it up in 01d2435babad2b1e2274ec9c5b59d6356f513304.
---
=> fix(title): use correct variable names

assets/css/0_reset.css, assets/css/1_main.css, layouts/partials/assets/css.html
=> feat(style): add css reset

i18n/en.toml, layouts/_default/home.html, layouts/partials/i18n/picker.html, layouts/partials/search.html
=> feat(i18n): use translation for the search bar and title all

assets/css/1_main.css, content/en/docs/glossary.md, content/en/x/array_reverse/_index.md, content/en/y/go/_index.md, layouts/partials/content.html
This allows for better discoverability whilst keeping the file naming convention set.
---
=> feat(aka): implement aka

layouts/partials/aka.html, layouts/partials/content.html
=> feat(aka): split into another file, hide directly

assets/css/1_main.css
Inspiration by https://www.swyx.io/css-100-bytes
---
=> feat(css): improve default style

assets/css/1_main.css, layouts/partials/taxonomy/tree.html
=> feat(taxonomy): improve x tree

assets/css/1_main.css, content/en/docs/about.md, content/fr/docs/about.md, i18n/de.toml, i18n/en.toml, layouts/_default/home.html, layouts/partials/i18n/link.html, layouts/partials/i18n/picker.html, layouts/partials/taxonomy/tree.html
Use pages instead of translation keys.
---
=> feat(about): add about page in en and fr

assets/css/1_main.css, content/en/404.md, content/en/docs/glossary/_index.md, content/en/docs/glossary/array.md, content/en/docs/glossary/dict.md, content/en/docs/glossary/http.md, hugo.toml, layouts/_default/glossary.html, layouts/_default/section.html, layouts/partials/debug.html
=> feat(glossary): make a section and update the layout

assets/css/1_main.css
=> fix(css): padding in pre and code conflicts

content/en/docs/contributing.md, content/en/docs/glossary/x.md, content/en/docs/glossary/y.md, content/en/x/_index.md, layouts/_default/glossary.html, layouts/_default/home.html, layouts/_default/taxonomy.html, layouts/partials/i18n/link.html, layouts/partials/i18n/picker.html, layouts/shortcodes/i18n/link.html
Also add a start of contribution.
---
=> feat(glossary): improve the rendering with anchor

assets/css/1_main.css, content/en/curl/http_request_get.md, content/en/docs/contributing.md, content/en/python/http_request_get.md, content/en/x/http_request_get/_index.md, i18n/en.toml, layouts/_default/single.html, layouts/_default/term.html, layouts/partials/references.html, layouts/partials/taxonomy/title.html, layouts/partials/title/text.html, layouts/shortcodes/note.html
Continue to refine the design and styles.
---
=> feat(content): add more content

content/en/docs/about.md
=> feat(about): write content

content/en/docs/privacy.md, layouts/partials/assets/js.html, layouts/partials/footer.html, layouts/partials/legal.html
=> feat(analytics): add goatcounter and privacy policy

content/en/docs/contributing.md
=> fix(lint): format

assets/css/1_main.css
=> fix(language-picker): align language right

content/en/y/go/_index.md, layouts/_default/single.html, layouts/partials/aka.html, layouts/partials/content.html
=> docs(go): add small description

config/_default/hugo.yaml, script/cascade
This reduces the number of false-positive research results.
---
=> feat(cascade): don't render glossary leaves

content/en/go/http_request_get.md, content/en/python/http_request_get.md
=> feat(http_request_get): add go example, simplify python example
